services:
  redis-node-1:
    image: redis:7.2-alpine
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly.aof --dbfilename dump.rdb
    container_name: "highload-messenger-redis-node-1"
    hostname: redis-node-1
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
        - redis-node-1-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.22.0.4

  redis-node-2:
    image: redis:7.2-alpine
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly.aof --dbfilename dump.rdb
    container_name: "highload-messenger-redis-node-2"
    hostname: redis-node-2
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
        - redis-node-2-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.22.0.7

  redis-node-3:
    image: redis:7.2-alpine
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly.aof --dbfilename dump.rdb
    container_name: "highload-messenger-redis-node-3"
    hostname: redis-node-3
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
        - redis-node-3-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.22.0.3

  redis-node-4:
    image: redis:7.2-alpine
    command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly.aof --dbfilename dump.rdb
    container_name: "highload-messenger-redis-node-4"
    hostname: redis-node-4
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
        - redis-node-4-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.22.0.6

  redis-node-5:
    image: redis:7.2-alpine
    command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly.aof --dbfilename dump.rdb
    container_name: "highload-messenger-redis-node-5"
    hostname: redis-node-5
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
        - redis-node-5-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.22.0.5

  redis-node-6:
    image: redis:7.2-alpine
    command: redis-server --port 7006 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly.aof --dbfilename dump.rdb
    container_name: "highload-messenger-redis-node-6"
    hostname: redis-node-6
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "7006:7006"
      - "17006:17006"
    volumes:
        - redis-node-6-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.22.0.2

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1