services:
  redis-node-1:
    image: redis:7.2-alpine
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly.aof --dbfilename dump.rdb
    container_name: "highload-messenger-redis-node-1"
    hostname: redis-node-1
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
        - redis-node-1-data:/data
    network_mode: "host"

  redis-node-2:
    image: redis:7.2-alpine
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly.aof --dbfilename dump.rdb
    container_name: "highload-messenger-redis-node-2"
    hostname: redis-node-2
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
        - redis-node-2-data:/data
    network_mode: "host"

  redis-node-3:
    image: redis:7.2-alpine
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly.aof --dbfilename dump.rdb
    container_name: "highload-messenger-redis-node-3"
    hostname: redis-node-3
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
        - redis-node-3-data:/data
    network_mode: "host"

  redis-node-4:
    image: redis:7.2-alpine
    command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly.aof --dbfilename dump.rdb
    container_name: "highload-messenger-redis-node-4"
    hostname: redis-node-4
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
        - redis-node-4-data:/data
    network_mode: "host"

  redis-node-5:
    image: redis:7.2-alpine
    command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly.aof --dbfilename dump.rdb
    container_name: "highload-messenger-redis-node-5"
    hostname: redis-node-5
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
        - redis-node-5-data:/data
    network_mode: "host"

  redis-node-6:
    image: redis:7.2-alpine
    command: redis-server --port 7006 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --appendfilename appendonly.aof --dbfilename dump.rdb
    container_name: "highload-messenger-redis-node-6"
    hostname: redis-node-6
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
        - redis-node-6-data:/data
    network_mode: "host"

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data: